#!/bin/bash

led=`cat /sys/class/leds/input3::capslock/brightness`

if [ $led -eq 0 ]; then
    echo "<span color='light green'> Capslock</span>"
else
    echo "<span color='red'> Capslock</span>"
fi
