#!/bin/bash

connections=`nmcli device status | grep wifi`

IFS=$'\n'

for connection in $connections
do
    status=`echo $connection | awk '{print $3}'`
    name=`echo $connection | awk '{print $4}'`
    if [ "$status" == "connected" ]; then
        echo "<span color='light green'> Wifi ($name)</span>"
        exit 0
    fi
done

echo "<span color='red'> No Wifi</span>"
